<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Assembly-CSharp</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net20</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>4</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\phase1_analysis\ipa_unpacked\Payload\DSSRacing.app\Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\..\phase1_analysis\ipa_unpacked\Payload\DSSRacing.app\Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>..\..\..\phase1_analysis\ipa_unpacked\Payload\DSSRacing.app\Data\Managed\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>..\..\..\phase1_analysis\ipa_unpacked\Payload\DSSRacing.app\Data\Managed\System.Xml.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>